# -*- coding: utf-8 -*-
# Copyright (C) 2016-2017  ITAAS

{
    'name': 'HR Extended',
    'version': '1.0',
    'category': 'Humance Resource',
    'sequence': 1,
    'summary': 'Humance Resource',
    'description': """
Human resource extended    """,
    'website': 'http://www.itaas.co.th/',
    'author': 'IT as a Service Co., Ltd.',
    'depends': [
        'hr',
        'hr_payroll',
        'hr_contract',
        'hr_holidays',
        'decimal_precision',
        # 'report',
        'hr_attendance',
        'hr_period',
        'hr_employee_benefit',
        'operating_unit',

        # 'payroll_public_holidays',
    ],
    'data': [
        # 'data/ir.cron.csv',
        'security/user_groups.xml',
        'security/ir_rule.xml',
        'hr_attendance_record.xml',
        'hr_payroll_view.xml',
        'hr_employee_view.xml',
        'hr_contract_view.xml',
        'hr_overtime_sequence.xml',
        # 'hr_holidays_view.xml',
        # # 'hr_holidays_workflow.xml',
        'views/hr_overtime_view.xml',
        'data/hr_salary_rule.xml',
        'views/hr_children.xml',
        'views/hr_education.xml',
        'views/hr_employee.xml',
        'views/hr_experience_exp.xml',
        'views/hr_health.xml',
        'views/hr_training.xml',
        'views/hr_training_line.xml',
        'views/contract_branch_view.xml',
        # 'views/hr_attendance_view.xml',
        # 'report/report_reg.xml',
        # 'report/employee_report.xml',
        # 'report/employee_report01.xml',
        # 'report/pngd91_report.xml',
        # 'report/sps1-02_report.xml',
        # 'report/sps1-03-1_report.xml',
        # 'report/sps1-03-2_report.xml',
        # 'report/sps1-10-1_report.xml',
        # 'report/sps1-10-2_report.xml',
        # 'report/sps6-09_report.xml',
        # 'report/report_payslip01.xml',
        # 'wizard/attendance_report_view.xml',
        # # 'wizard/payslip_report_view.xml',
        # 'security/ir.model.access.csv',

    ],
    'demo': [],
    'css': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
